gcp:
project_id: "addv1-td-alldata-app"
region: "us-central1"
zone: "us-central1-a"

# Cloud Run Configuration
service_name: "etl-dispatcher"
job_name: "etl-processor"
#service_url: "https://etl-dispatcher-xxxxx-uc.a.run.app"

# Database Configuration
database:
  url: "mysql+pymysql://username:password@host:3306/database_name"
  host: "your-mysql-host"
  port: 3306
  username: "your-username"
  password: "your-password"
  database: "your-database"

# GCS Configuration
gcs:
  bucket_name: "sm-ingest-dev"
  import_path: "imports"

# VPC Configuration (if using private database)
vpc:
  connector_name: "etl-vpc-connector"
  connector_region: "us-central1"

# Service Account
service_account: "shop-pro-functions-sa@addv1-td-alldata-app.iam.gserviceaccount.com"
build_service_account: "projects/adst1-td-alldata-app/serviceAccounts/mobile-team-service-account@adst1-td-alldata-app.iam.gserviceaccount.com"

